/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AthenaResults": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "CompactionFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Dashboard": {
      "type": "sst.aws.React"
      "url": string
    }
    "EventData": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "EventsFirehoseStream": {
      "name": string
      "type": "aws.kinesis/firehoseDeliveryStream.FirehoseDeliveryStream"
    }
    "EventsGlueTable": {
      "arn": string
      "databaseName": string
      "name": string
      "type": "aws.glue/catalogTable.CatalogTable"
    }
    "GlueCatalogDatabase": {
      "arn": string
      "name": string
      "type": "aws.glue/catalogDatabase.CatalogDatabase"
    }
    "IcebergInitFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "IngestFn": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "InitialEventsFirehoseStream": {
      "name": string
      "type": "aws.kinesis/firehoseDeliveryStream.FirehoseDeliveryStream"
    }
    "InitialEventsGlueTable": {
      "arn": string
      "databaseName": string
      "name": string
      "type": "aws.glue/catalogTable.CatalogTable"
    }
    "ManagementApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "PreferencesFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PublicRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "QueryFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SitesFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SitesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "UserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "UserPreferencesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}